// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/Employee.proto

package com.protobuf.producer.protobufproducer.emp;

public final class Employee {
  private Employee() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Emp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string emp_name = 2;</code>
     * @return The empName.
     */
    java.lang.String getEmpName();
    /**
     * <code>string emp_name = 2;</code>
     * @return The bytes for empName.
     */
    com.google.protobuf.ByteString
        getEmpNameBytes();

    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    java.util.List<com.protobuf.producer.protobufproducer.emp.Employee.Company> 
        getCompaniesList();
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    com.protobuf.producer.protobufproducer.emp.Employee.Company getCompanies(int index);
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    int getCompaniesCount();
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    java.util.List<? extends com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder> 
        getCompaniesOrBuilderList();
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder getCompaniesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code demo.Emp}
   */
  public static final class Emp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Emp)
      EmpOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Emp.newBuilder() to construct.
    private Emp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Emp() {
      empName_ = "";
      companies_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Emp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Emp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              empName_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                companies_ = new java.util.ArrayList<com.protobuf.producer.protobufproducer.emp.Employee.Company>();
                mutable_bitField0_ |= 0x00000001;
              }
              companies_.add(
                  input.readMessage(com.protobuf.producer.protobufproducer.emp.Employee.Company.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          companies_ = java.util.Collections.unmodifiableList(companies_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Emp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Emp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.producer.protobufproducer.emp.Employee.Emp.class, com.protobuf.producer.protobufproducer.emp.Employee.Emp.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int EMP_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object empName_;
    /**
     * <code>string emp_name = 2;</code>
     * @return The empName.
     */
    @java.lang.Override
    public java.lang.String getEmpName() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        empName_ = s;
        return s;
      }
    }
    /**
     * <code>string emp_name = 2;</code>
     * @return The bytes for empName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmpNameBytes() {
      java.lang.Object ref = empName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANIES_FIELD_NUMBER = 3;
    private java.util.List<com.protobuf.producer.protobufproducer.emp.Employee.Company> companies_;
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.protobuf.producer.protobufproducer.emp.Employee.Company> getCompaniesList() {
      return companies_;
    }
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder> 
        getCompaniesOrBuilderList() {
      return companies_;
    }
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    @java.lang.Override
    public int getCompaniesCount() {
      return companies_.size();
    }
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    @java.lang.Override
    public com.protobuf.producer.protobufproducer.emp.Employee.Company getCompanies(int index) {
      return companies_.get(index);
    }
    /**
     * <code>repeated .demo.Company companies = 3;</code>
     */
    @java.lang.Override
    public com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder getCompaniesOrBuilder(
        int index) {
      return companies_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getEmpNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, empName_);
      }
      for (int i = 0; i < companies_.size(); i++) {
        output.writeMessage(3, companies_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getEmpNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, empName_);
      }
      for (int i = 0; i < companies_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, companies_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protobuf.producer.protobufproducer.emp.Employee.Emp)) {
        return super.equals(obj);
      }
      com.protobuf.producer.protobufproducer.emp.Employee.Emp other = (com.protobuf.producer.protobufproducer.emp.Employee.Emp) obj;

      if (getId()
          != other.getId()) return false;
      if (!getEmpName()
          .equals(other.getEmpName())) return false;
      if (!getCompaniesList()
          .equals(other.getCompaniesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EMP_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getEmpName().hashCode();
      if (getCompaniesCount() > 0) {
        hash = (37 * hash) + COMPANIES_FIELD_NUMBER;
        hash = (53 * hash) + getCompaniesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protobuf.producer.protobufproducer.emp.Employee.Emp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Emp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Emp)
        com.protobuf.producer.protobufproducer.emp.Employee.EmpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Emp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Emp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.producer.protobufproducer.emp.Employee.Emp.class, com.protobuf.producer.protobufproducer.emp.Employee.Emp.Builder.class);
      }

      // Construct using com.protobuf.producer.protobufproducer.emp.Employee.Emp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCompaniesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        empName_ = "";

        if (companiesBuilder_ == null) {
          companies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          companiesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Emp_descriptor;
      }

      @java.lang.Override
      public com.protobuf.producer.protobufproducer.emp.Employee.Emp getDefaultInstanceForType() {
        return com.protobuf.producer.protobufproducer.emp.Employee.Emp.getDefaultInstance();
      }

      @java.lang.Override
      public com.protobuf.producer.protobufproducer.emp.Employee.Emp build() {
        com.protobuf.producer.protobufproducer.emp.Employee.Emp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protobuf.producer.protobufproducer.emp.Employee.Emp buildPartial() {
        com.protobuf.producer.protobufproducer.emp.Employee.Emp result = new com.protobuf.producer.protobufproducer.emp.Employee.Emp(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.empName_ = empName_;
        if (companiesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            companies_ = java.util.Collections.unmodifiableList(companies_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.companies_ = companies_;
        } else {
          result.companies_ = companiesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.producer.protobufproducer.emp.Employee.Emp) {
          return mergeFrom((com.protobuf.producer.protobufproducer.emp.Employee.Emp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.producer.protobufproducer.emp.Employee.Emp other) {
        if (other == com.protobuf.producer.protobufproducer.emp.Employee.Emp.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getEmpName().isEmpty()) {
          empName_ = other.empName_;
          onChanged();
        }
        if (companiesBuilder_ == null) {
          if (!other.companies_.isEmpty()) {
            if (companies_.isEmpty()) {
              companies_ = other.companies_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCompaniesIsMutable();
              companies_.addAll(other.companies_);
            }
            onChanged();
          }
        } else {
          if (!other.companies_.isEmpty()) {
            if (companiesBuilder_.isEmpty()) {
              companiesBuilder_.dispose();
              companiesBuilder_ = null;
              companies_ = other.companies_;
              bitField0_ = (bitField0_ & ~0x00000001);
              companiesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCompaniesFieldBuilder() : null;
            } else {
              companiesBuilder_.addAllMessages(other.companies_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.producer.protobufproducer.emp.Employee.Emp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.producer.protobufproducer.emp.Employee.Emp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object empName_ = "";
      /**
       * <code>string emp_name = 2;</code>
       * @return The empName.
       */
      public java.lang.String getEmpName() {
        java.lang.Object ref = empName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          empName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emp_name = 2;</code>
       * @return The bytes for empName.
       */
      public com.google.protobuf.ByteString
          getEmpNameBytes() {
        java.lang.Object ref = empName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emp_name = 2;</code>
       * @param value The empName to set.
       * @return This builder for chaining.
       */
      public Builder setEmpName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        empName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emp_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmpName() {
        
        empName_ = getDefaultInstance().getEmpName();
        onChanged();
        return this;
      }
      /**
       * <code>string emp_name = 2;</code>
       * @param value The bytes for empName to set.
       * @return This builder for chaining.
       */
      public Builder setEmpNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        empName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.protobuf.producer.protobufproducer.emp.Employee.Company> companies_ =
        java.util.Collections.emptyList();
      private void ensureCompaniesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          companies_ = new java.util.ArrayList<com.protobuf.producer.protobufproducer.emp.Employee.Company>(companies_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protobuf.producer.protobufproducer.emp.Employee.Company, com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder, com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder> companiesBuilder_;

      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public java.util.List<com.protobuf.producer.protobufproducer.emp.Employee.Company> getCompaniesList() {
        if (companiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(companies_);
        } else {
          return companiesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public int getCompaniesCount() {
        if (companiesBuilder_ == null) {
          return companies_.size();
        } else {
          return companiesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public com.protobuf.producer.protobufproducer.emp.Employee.Company getCompanies(int index) {
        if (companiesBuilder_ == null) {
          return companies_.get(index);
        } else {
          return companiesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder setCompanies(
          int index, com.protobuf.producer.protobufproducer.emp.Employee.Company value) {
        if (companiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompaniesIsMutable();
          companies_.set(index, value);
          onChanged();
        } else {
          companiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder setCompanies(
          int index, com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder builderForValue) {
        if (companiesBuilder_ == null) {
          ensureCompaniesIsMutable();
          companies_.set(index, builderForValue.build());
          onChanged();
        } else {
          companiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder addCompanies(com.protobuf.producer.protobufproducer.emp.Employee.Company value) {
        if (companiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompaniesIsMutable();
          companies_.add(value);
          onChanged();
        } else {
          companiesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder addCompanies(
          int index, com.protobuf.producer.protobufproducer.emp.Employee.Company value) {
        if (companiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompaniesIsMutable();
          companies_.add(index, value);
          onChanged();
        } else {
          companiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder addCompanies(
          com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder builderForValue) {
        if (companiesBuilder_ == null) {
          ensureCompaniesIsMutable();
          companies_.add(builderForValue.build());
          onChanged();
        } else {
          companiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder addCompanies(
          int index, com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder builderForValue) {
        if (companiesBuilder_ == null) {
          ensureCompaniesIsMutable();
          companies_.add(index, builderForValue.build());
          onChanged();
        } else {
          companiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder addAllCompanies(
          java.lang.Iterable<? extends com.protobuf.producer.protobufproducer.emp.Employee.Company> values) {
        if (companiesBuilder_ == null) {
          ensureCompaniesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, companies_);
          onChanged();
        } else {
          companiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder clearCompanies() {
        if (companiesBuilder_ == null) {
          companies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          companiesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public Builder removeCompanies(int index) {
        if (companiesBuilder_ == null) {
          ensureCompaniesIsMutable();
          companies_.remove(index);
          onChanged();
        } else {
          companiesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder getCompaniesBuilder(
          int index) {
        return getCompaniesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder getCompaniesOrBuilder(
          int index) {
        if (companiesBuilder_ == null) {
          return companies_.get(index);  } else {
          return companiesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public java.util.List<? extends com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder> 
           getCompaniesOrBuilderList() {
        if (companiesBuilder_ != null) {
          return companiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(companies_);
        }
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder addCompaniesBuilder() {
        return getCompaniesFieldBuilder().addBuilder(
            com.protobuf.producer.protobufproducer.emp.Employee.Company.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder addCompaniesBuilder(
          int index) {
        return getCompaniesFieldBuilder().addBuilder(
            index, com.protobuf.producer.protobufproducer.emp.Employee.Company.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Company companies = 3;</code>
       */
      public java.util.List<com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder> 
           getCompaniesBuilderList() {
        return getCompaniesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protobuf.producer.protobufproducer.emp.Employee.Company, com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder, com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder> 
          getCompaniesFieldBuilder() {
        if (companiesBuilder_ == null) {
          companiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protobuf.producer.protobufproducer.emp.Employee.Company, com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder, com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder>(
                  companies_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          companies_ = null;
        }
        return companiesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Emp)
    }

    // @@protoc_insertion_point(class_scope:demo.Emp)
    private static final com.protobuf.producer.protobufproducer.emp.Employee.Emp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protobuf.producer.protobufproducer.emp.Employee.Emp();
    }

    public static com.protobuf.producer.protobufproducer.emp.Employee.Emp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Emp>
        PARSER = new com.google.protobuf.AbstractParser<Emp>() {
      @java.lang.Override
      public Emp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Emp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Emp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Emp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protobuf.producer.protobufproducer.emp.Employee.Emp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CompanyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Company)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string company_name = 2;</code>
     * @return The companyName.
     */
    java.lang.String getCompanyName();
    /**
     * <code>string company_name = 2;</code>
     * @return The bytes for companyName.
     */
    com.google.protobuf.ByteString
        getCompanyNameBytes();

    /**
     * <code>string location = 3;</code>
     * @return The location.
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 3;</code>
     * @return The bytes for location.
     */
    com.google.protobuf.ByteString
        getLocationBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code demo.Company}
   */
  public static final class Company extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Company)
      CompanyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Company.newBuilder() to construct.
    private Company(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Company() {
      companyName_ = "";
      location_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Company();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Company(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              companyName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Company_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Company_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.producer.protobufproducer.emp.Employee.Company.class, com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int COMPANY_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object companyName_;
    /**
     * <code>string company_name = 2;</code>
     * @return The companyName.
     */
    @java.lang.Override
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyName_ = s;
        return s;
      }
    }
    /**
     * <code>string company_name = 2;</code>
     * @return The bytes for companyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object location_;
    /**
     * <code>string location = 3;</code>
     * @return The location.
     */
    @java.lang.Override
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 3;</code>
     * @return The bytes for location.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getCompanyNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, companyName_);
      }
      if (!getLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, location_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getCompanyNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, companyName_);
      }
      if (!getLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, location_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protobuf.producer.protobufproducer.emp.Employee.Company)) {
        return super.equals(obj);
      }
      com.protobuf.producer.protobufproducer.emp.Employee.Company other = (com.protobuf.producer.protobufproducer.emp.Employee.Company) obj;

      if (getId()
          != other.getId()) return false;
      if (!getCompanyName()
          .equals(other.getCompanyName())) return false;
      if (!getLocation()
          .equals(other.getLocation())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + COMPANY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyName().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protobuf.producer.protobufproducer.emp.Employee.Company parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protobuf.producer.protobufproducer.emp.Employee.Company prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Company}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Company)
        com.protobuf.producer.protobufproducer.emp.Employee.CompanyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Company_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Company_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.producer.protobufproducer.emp.Employee.Company.class, com.protobuf.producer.protobufproducer.emp.Employee.Company.Builder.class);
      }

      // Construct using com.protobuf.producer.protobufproducer.emp.Employee.Company.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        companyName_ = "";

        location_ = "";

        email_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.producer.protobufproducer.emp.Employee.internal_static_demo_Company_descriptor;
      }

      @java.lang.Override
      public com.protobuf.producer.protobufproducer.emp.Employee.Company getDefaultInstanceForType() {
        return com.protobuf.producer.protobufproducer.emp.Employee.Company.getDefaultInstance();
      }

      @java.lang.Override
      public com.protobuf.producer.protobufproducer.emp.Employee.Company build() {
        com.protobuf.producer.protobufproducer.emp.Employee.Company result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protobuf.producer.protobufproducer.emp.Employee.Company buildPartial() {
        com.protobuf.producer.protobufproducer.emp.Employee.Company result = new com.protobuf.producer.protobufproducer.emp.Employee.Company(this);
        result.id_ = id_;
        result.companyName_ = companyName_;
        result.location_ = location_;
        result.email_ = email_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.producer.protobufproducer.emp.Employee.Company) {
          return mergeFrom((com.protobuf.producer.protobufproducer.emp.Employee.Company)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.producer.protobufproducer.emp.Employee.Company other) {
        if (other == com.protobuf.producer.protobufproducer.emp.Employee.Company.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getCompanyName().isEmpty()) {
          companyName_ = other.companyName_;
          onChanged();
        }
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.producer.protobufproducer.emp.Employee.Company parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.producer.protobufproducer.emp.Employee.Company) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object companyName_ = "";
      /**
       * <code>string company_name = 2;</code>
       * @return The companyName.
       */
      public java.lang.String getCompanyName() {
        java.lang.Object ref = companyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          companyName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string company_name = 2;</code>
       * @return The bytes for companyName.
       */
      public com.google.protobuf.ByteString
          getCompanyNameBytes() {
        java.lang.Object ref = companyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company_name = 2;</code>
       * @param value The companyName to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        companyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string company_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompanyName() {
        
        companyName_ = getDefaultInstance().getCompanyName();
        onChanged();
        return this;
      }
      /**
       * <code>string company_name = 2;</code>
       * @param value The bytes for companyName to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        companyName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 3;</code>
       * @return The location.
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       * @return The bytes for location.
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       * @param value The bytes for location to set.
       * @return This builder for chaining.
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Company)
    }

    // @@protoc_insertion_point(class_scope:demo.Company)
    private static final com.protobuf.producer.protobufproducer.emp.Employee.Company DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protobuf.producer.protobufproducer.emp.Employee.Company();
    }

    public static com.protobuf.producer.protobufproducer.emp.Employee.Company getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Company>
        PARSER = new com.google.protobuf.AbstractParser<Company>() {
      @java.lang.Override
      public Company parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Company(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Company> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Company> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protobuf.producer.protobufproducer.emp.Employee.Company getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Emp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Emp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Company_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Company_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030resources/Employee.proto\022\004demo\"E\n\003Emp\022" +
      "\n\n\002id\030\001 \001(\005\022\020\n\010emp_name\030\002 \001(\t\022 \n\tcompani" +
      "es\030\003 \003(\0132\r.demo.Company\"L\n\007Company\022\n\n\002id" +
      "\030\001 \001(\005\022\024\n\014company_name\030\002 \001(\t\022\020\n\010location" +
      "\030\003 \001(\t\022\r\n\005email\030\004 \001(\tB,\n*com.protobuf.pr" +
      "oducer.protobufproducer.empb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_Emp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Emp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Emp_descriptor,
        new java.lang.String[] { "Id", "EmpName", "Companies", });
    internal_static_demo_Company_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Company_descriptor,
        new java.lang.String[] { "Id", "CompanyName", "Location", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
